spring:
  application:
    name: store
  datasource:
<<<<<<< HEAD
    url: jdbc:postgresql://localhost:5432/mydb
    username: admin
    password: 123456
=======
    url: jdbc:postgresql://localhost:5432/data
    username: postgres
    password: 111444
>>>>>>> main
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
<<<<<<< HEAD


        default_schema: ecommerce

=======
        default_schema: ecommerce   # ðŸ‘ˆ THÃŠM DÃ’NG NÃ€Y
>>>>>>> main
server:
  port: 8080
logging:
  level:
    org.springframework: INFO
    com.example.backend: DEBUG      # ðŸ‘ˆ package tháº­t cá»§a báº¡n lÃ  com.example.backend (khÃ´ng pháº£i com.example.TeeHub)
